- name: Become Demo 
  hosts: servera*
  gather_facts: false
  become: false
  roles:
    - role: web_server
      become: true
  tasks:
    - name: Create a File
      ansible.builtin.copy:
        dest: /tmp/abc.txt
        content: "Hello IBM Users"
        mode: 0644

    - name: Open Firewalld Port
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      become: true

    - name: Web Server Root Permission
      block:
          - name: Install Web Package
            ansible.builtin.dnf:
              name: httpd
              state: present

          - name: Deploy an App
            ansible.builtin.copy:
              content: "IBM Index Page"
              dest: /var/www/html/index.html
              mode: 0644

          - name: Start Web Service
            ansible.builtin.service:
              name: httpd
              state: started
      become: true
