- name: Loop with lookup Dict/List Demo
  hosts: servera*
  gather_facts: false
  vars_files:
    - vars/outside_vars.yml
    - vars/users.yml
  tasks:
    - name: Print Simple List
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ lookup('ansible.builtin.list', simple_list) }}"
      # with_items: "{{ simple_list }}"
      # with_list: "{{ simple_list }}"
      # loop: "{{ simple_list }}"
      # loop came from ANsible 2.5

    - name: Print Complex List
      ansible.builtin.debug:
        msg: "{{ item.name }} // {{ item.value }}"
      loop: "{{ lookup('ansible.builtin.list', complex_list) }}"
      # with_list: "{{ complex_list }}"
      # loop: "{{ complex_list }}"

    - name: Print Dictionary
      ansible.builtin.debug:
        msg: "{{ item['key'] }} == {{ item['value'] }}"
      loop: "{{ lookup('ansible.builtin.dict', mydict) }}"
        # msg: "{{ item.key }} == {{ item.value }}"
      # with_dict: "{{ mydict }}"
      # loop: "{{ mydict | dict2items }}"
      # loop ONLY take List/Array
    
    - name: Difference between lookup and query
      ansible.builtin.debug:
        msg: "{{ query('ansible.builtin.sequence','start=0 end=4 format=eth%x') }}"
        # msg: "{{ lookup('ansible.builtin.sequence','start=0 end=4 format=eth%x') }}"

    - name: Print a Sequence
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ q('ansible.builtin.sequence','start=0 end=4 format=eth%x') }}"
        # msg: "eth{{ item }}"
      # with_sequence: start=0 end=4 format=eth%x

    - name: Print File Content WARNING
      ansible.builtin.debug:
        msg: "{{ q('ansible.builtin.file', '/etc/passwddd') }}"
        #msg: "{{ q('ansible.builtin.file', '/etc/passwddd', errors='warn') }}"
      ignore_errors: true

    - name: Print Content of folder
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', '{{ item }}') }}"
        # msg: "{{ item }}"
      loop: "{{ query('ansible.builtin.fileglob','vars/*') }}"
      # with_fileglob:
      #   - /etc/ssh/*

    - name: Print File Content
      ansible.builtin.debug:
        msg: "{{ item }}"
        # msg: "{{ q('ansible.builtin.lines', 'cat /etc/passwd') }}"
      loop: "{{ q('ansible.builtin.lines', 'cat /etc/passwd') }}"


    - name: Flatten Filter/plugin list
      ansible.builtin.debug:
        msg: "YOUME_{{ item }}"
      loop: "{{ lookup('ansible.builtin.flattened', nested_list) }}"
      # with_flattened: "{{ nested_list }}"
      # loop: "{{ nested_list | flatten }}"
      #
    - name: Lookup Subelements/loop around sublist/nested list
      ansible.builtin.debug:
        msg: "{{ item[1] }} ** {{ item[0].name }}"
      loop: "{{ lookup('ansible.builtin.subelements', users,'mysql.hosts') }}"
      # with_subelements:
      #   - "{{ users }}"
      #   - mysql.hosts
        # - authorized
