### REQUIRED
namespace: ibm

name: finance
version: 3.0.0
readme: README.md

authors:
- marin<martin@ibm.com>

description: Created by Martin and Helped by Randeep
license:
- GPL-2.0-or-later

license_file: ''
tags: []

dependencies:
  ansible.posix: '>=1.3.0'
  #community.general: '>=1.0.0'
  community.mysql: '>=3.10.0'

repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []
